modLoader = "javafml"
loaderVersion = "38,)"
license = "GNU Lesser General Public License v3.0"

[[mods]]
modId = "raised"
version = "${version}"
displayName = "Raised"
displayURL = "https://github.com/yurisuika/Raised"
issueTrackerURL = "https://github.com/yurisuika/Raised/issues"
logoFile = "icon.png"
authors = "yurisuika"
description = '''
Raises the hotbar so the selector is not cut off!
'''

[[dependencies.raised]]
modId="minecraft"
mandatory=true
versionRange="[1.18,1.19)"
ordering="NONE"
side="CLIENT"

[[dependencies.raised]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.raised]]
modId = "botania"
mandatory = false
versionRange = "[1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.raised]]
modId = "create"
mandatory = false
versionRange = "[0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.raised]]
modId = "detailab"
mandatory = false
versionRange = "[2,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.raised]]
modId = "healthoverlay"
mandatory = false
versionRange = "[6,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.raised]]
modId = "inventorio"
mandatory = false
versionRange = "[1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.raised]]
modId = "inventoryprofilesnext"
mandatory = false
versionRange = "[1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.raised]]
modId = "levelhearts"
mandatory = false
versionRange = "[1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.raised]]
modId = "quark"
mandatory = false
versionRange = "[3,)"
ordering = "NONE"
side = "CLIENT"