modLoader = "javafml"
loaderVersion = "38,)"
license = "GNU Lesser General Public License v3.0"

[[mods]]
modId = "raised-detailarmorbar"
version = "${version}"
displayName = "Raised + Detail Armor Bar"
displayTest = "IGNORE_ALL_VERSION"
displayURL = "https://github.com/yurisuika/Raised"
issueTrackerURL = "https://github.com/yurisuika/Raised/issues"
logoFile = "icon.png"
authors = "yurisuika"
description = '''
Adds support for Detail Armor Bar to Raised!
'''

[[dependencies.raised-detailarmorbar]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.19)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.raised-detailarmorbar]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.raised-detailarmorbar]]
modId = "raised"
mandatory = true
versionRange = "[2,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.raised-detailarmorbar]]
modId = "detailab"
mandatory = true
versionRange = "[2,)"
ordering = "NONE"
side = "CLIENT"