modLoader = "javafml"
loaderVersion = "38,)"
license = "GNU Lesser General Public License v3.0"

[[mods]]
modId = "raisedxinventorio"
version = "${version}"
displayName = "Raised x Inventorio"
displayTest = "IGNORE_ALL_VERSION"
displayURL = "https://github.com/yurisuika/Raised"
issueTrackerURL = "https://github.com/yurisuika/Raised/issues"
logoFile = "icon.png"
authors = "yurisuika"
description = '''
Adds support for Inventorio to Raised!
'''

[[dependencies.raisedxinventorio]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.19)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.raisedxinventorio]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.raisedxinventorio]]
modId = "raised"
mandatory = true
versionRange = "[2,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.raisedxinventorio]]
modId = "inventorio"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "CLIENT"