name: Build

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - run: chmod +x gradlew
      - run: ./gradlew build --stacktrace --info
      - uses: actions/upload-artifact@v3
        with:
          name: Raised
          path: build/libs/
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        with:
          name: Raised + Appleskin
          path: raised-appleskin/build/libs/
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        with:
          name: Raised + Detail Armor Bar
          path: raised-detailarmorbar/build/libs/
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        with:
          name: Raised + Inventorio
          path: raised-inventorio/build/libs/
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        with:
          name: Raised + Inventory Profiles Next
          path: raised-inventoryprofilesnext/build/libs/
          if-no-files-found: error